spring:
  application:
    name: SGHSS

  jackson:
    date-format: "yyyy-MM-dd HH:mm"
    default-property-inclusion: non_null
    deserialization:
      fail-on-null-for-primitives: true
    serialization:
      write-dates-as-timestamps: false

  datasource:
    url: jdbc:postgresql://localhost:5432/SGHSS
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: false

  sql:
    init:
      mode: always

api:
  app:
    jwtSecret: ${SECRET:45da2ed9f455817623087c49390b2ab9e4d38421c20f5a282a877f8e6662c67b361a0f7bd810cbca8e471e183c41d9a648b057aed0369b67078c6d73e38d}
    jwtExpirationMs: 86400000

logging:
  level:
    org.springframework.security: DEBUG

springdoc:
  swagger-ui:
    display-request-duration: true
    syntax-highlight:
      theme: nord
    defaultModelsExpandDepth: 1
